import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import WhatsAppButton from "@/components/Whatsapp/page";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-montserrat antialiased bg-white`}>
        <div className="fixed top-0 left-0 right-0 z-[997]">
        <Navbar />
        </div>
        <main className="pb-48 md:pb-40 bg-white">
          {children}
        </main>
        <div className="fixed bottom-42 md:bottom-38 right-8 z-[999]">
          <WhatsAppButton />
        </div>
        
       {/* <div className="fixed bottom-0 left-0 right-0 z-[998]">
          <AppleStyleDock />
        </div> */}
      </body>
    </html>
  );
}
